---
- name: Deploy Employee Management Application
  hosts: app
  become: true

  tasks:
    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - php-mysql
        state: present
        update_cache: true

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copy application files
      copy:
        src: app/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Set database password
      lineinfile:
        path: /etc/environment
        line: 'DB_PASSWORD="PitCLtV8pvIoT6MPRBtgDPGhDoAbCZ4Q"'
        create: true

    - name: Set database host
      lineinfile:
        path: /etc/environment
        line: 'DB_HOST="employee-management-db.cliumscw44qs.ap-south-1.rds.amazonaws.com"'
        create: true

    - name: Set database user
      lineinfile:
        path: /etc/environment
        line: 'DB_USER="admin"'
        create: true

    - name: Set database name
      lineinfile:
        path: /etc/environment
        line: 'DB_NAME="employee_db"'
        create: true

    - name: Remove test homepage
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Run database setup
      command: php /var/www/html/setup.php
      register: db_setup

    - name: Show database setup result
      debug:
        msg: "{{ db_setup.stdout }}"
